import type { Fact, Manifest } from '../types.js';

export const START = '<!-- warmstart:start -->';
export const END = '<!-- warmstart:end -->';

function stamp(f: Fact): string {
  switch (f.status) {
    case 'passed': return `✓ passed — ${f.platform?.os}/${f.platform?.arch}, ${f.platform?.node}, ${f.lastVerified}`;
    case 'flaky': return `~ flaky (${f.passes}/${f.runs} passes)`;
    case 'env-missing': return '⚠ unverified (env-missing — command may be correct)';
    case 'destructive': return '⚠ unverified (not-run: destructive)';
    case 'timeout': return '⚠ unverified (timeout)';
    default: return '✗ failed';
  }
}

export function renderAgentsMd(m: Manifest): string {
  const lines = [START, '', '# Dev loop (generated by warmstart — do not edit inside the markers)', ''];
  const byCat = new Map<string, Fact[]>();
  for (const f of m.facts) {
    const arr = byCat.get(f.category) ?? [];
    arr.push(f);
    byCat.set(f.category, arr);
  }
  for (const [cat, facts] of byCat) {
    lines.push(`## ${cat}`);
    for (const f of facts) lines.push(`- \`${f.command}\` — ${stamp(f)}`);
    lines.push('');
  }
  lines.push(`_Generated ${m.generatedAt}. Stamps mean "ran here, then" — not a portability guarantee._`, '', END, '');
  return lines.join('\n');
}
